/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package untan.ziman.rekapitulasikesehatanberingin;

import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author USER
 */
public class ImunisasiView extends javax.swing.JFrame {

    /**
     * Creates new form ImunisasiView
     */
    ArrayList<Imunisasi> imunisasiList;
    String header[]=new String[]{"PWS Imunisasi","Nama Dusun","Sasaran","Perolehan","Bulan","Persentase"};
    DefaultTableModel dtmi;
    int row,col;
    public ImunisasiView() {
        initComponents();
        imunisasiList=new ArrayList<>();
        dtmi=new DefaultTableModel(header,0);
        tbImunisasi.setModel(dtmi);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imunView = new javax.swing.JPanel();
        lbTitleImunisasi = new javax.swing.JLabel();
        lbImunisasi = new javax.swing.JLabel();
        lbNamaDusunI = new javax.swing.JLabel();
        lbSasaranI = new javax.swing.JLabel();
        lbBulanI = new javax.swing.JLabel();
        cbImunisasi = new javax.swing.JComboBox<>();
        cbBulanI = new javax.swing.JComboBox<>();
        tfNamaDusunI = new javax.swing.JTextField();
        tfSasaranI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbImunisasi = new javax.swing.JTable();
        lbPerolehanI = new javax.swing.JLabel();
        tfPerolehanI = new javax.swing.JTextField();
        btAddI = new javax.swing.JButton();
        btDeleteI = new javax.swing.JButton();
        btUpdateI = new javax.swing.JButton();
        btExportI = new javax.swing.JButton();

        setTitle("Perhitungan Data Imunisasi");
        setPreferredSize(new java.awt.Dimension(900, 700));
        setResizable(false);

        imunView.setBackground(new java.awt.Color(142, 68, 173));

        lbTitleImunisasi.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        lbTitleImunisasi.setForeground(new java.awt.Color(0, 0, 0));
        lbTitleImunisasi.setText("Perhitungan PWS Imunisasi");

        lbImunisasi.setForeground(new java.awt.Color(0, 0, 0));
        lbImunisasi.setText("PWS Imunisasi : ");

        lbNamaDusunI.setForeground(new java.awt.Color(0, 0, 0));
        lbNamaDusunI.setText("Nama Dusun : ");

        lbSasaranI.setForeground(new java.awt.Color(0, 0, 0));
        lbSasaranI.setText("Sasaran : ");

        lbBulanI.setForeground(new java.awt.Color(0, 0, 0));
        lbBulanI.setText("Bulan : ");

        cbImunisasi.setBackground(new java.awt.Color(255, 255, 255));
        cbImunisasi.setForeground(new java.awt.Color(0, 0, 0));
        cbImunisasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HBO", "BCG", "Polio 1", "DPT-HB-Hib 1", "POLIO 2", "DPT-HB-Hib 2", "POLIO 3", "DPT-HB-Hib 3", "POLIO 4", "IPV", "Campak", "Campak Lengkap", "DPT-HB-Hib Lanjutan", "Campak Lanjutan" }));
        cbImunisasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbImunisasiActionPerformed(evt);
            }
        });

        cbBulanI.setBackground(new java.awt.Color(255, 255, 255));
        cbBulanI.setForeground(new java.awt.Color(0, 0, 0));
        cbBulanI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Januari", "2. Februari", "3. Maret", "4. April", "5. Mei", "6. Juni", "7. Juli", "8. Agustus", "9. September", "10. Oktober", "11. November", "12. Desember" }));

        tfNamaDusunI.setBackground(new java.awt.Color(255, 255, 255));
        tfNamaDusunI.setForeground(new java.awt.Color(0, 0, 0));

        tfSasaranI.setBackground(new java.awt.Color(255, 255, 255));
        tfSasaranI.setForeground(new java.awt.Color(0, 0, 0));

        tbImunisasi.setBackground(new java.awt.Color(255, 255, 255));
        tbImunisasi.setForeground(new java.awt.Color(0, 0, 0));
        tbImunisasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PWS Imunisasi", "Nama Dusun", "Sasaran", "Perolehan", "Bulan", "Persentase"
            }
        ));
        tbImunisasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbImunisasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbImunisasi);

        lbPerolehanI.setForeground(new java.awt.Color(0, 0, 0));
        lbPerolehanI.setText("Perolehan : ");

        tfPerolehanI.setBackground(new java.awt.Color(255, 255, 255));
        tfPerolehanI.setForeground(new java.awt.Color(0, 0, 0));

        btAddI.setForeground(new java.awt.Color(0, 0, 0));
        btAddI.setText("Add");
        btAddI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddIActionPerformed(evt);
            }
        });

        btDeleteI.setForeground(new java.awt.Color(0, 0, 0));
        btDeleteI.setText("Delete");
        btDeleteI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteIActionPerformed(evt);
            }
        });

        btUpdateI.setForeground(new java.awt.Color(0, 0, 0));
        btUpdateI.setText("Update");
        btUpdateI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateIActionPerformed(evt);
            }
        });

        btExportI.setForeground(new java.awt.Color(0, 0, 0));
        btExportI.setText("Export to .xlsx");
        btExportI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExportIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imunViewLayout = new javax.swing.GroupLayout(imunView);
        imunView.setLayout(imunViewLayout);
        imunViewLayout.setHorizontalGroup(
            imunViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imunViewLayout.createSequentialGroup()
                .addGroup(imunViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imunViewLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(lbTitleImunisasi))
                    .addGroup(imunViewLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(imunViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbImunisasi)
                            .addComponent(lbNamaDusunI, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbBulanI, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbPerolehanI, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSasaranI, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(imunViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbBulanI, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbImunisasi, 0, 282, Short.MAX_VALUE)
                            .addComponent(tfNamaDusunI)
                            .addComponent(tfSasaranI)
                            .addComponent(tfPerolehanI))
                        .addGap(56, 56, 56)
                        .addGroup(imunViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btDeleteI, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(btAddI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(imunViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btExportI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btUpdateI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(imunViewLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        imunViewLayout.setVerticalGroup(
            imunViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imunViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitleImunisasi)
                .addGap(38, 38, 38)
                .addGroup(imunViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbImunisasi, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbImunisasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(imunViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNamaDusunI)
                    .addComponent(tfNamaDusunI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(imunViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSasaranI)
                    .addComponent(tfSasaranI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(imunViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imunViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbPerolehanI)
                        .addComponent(tfPerolehanI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imunViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btUpdateI)
                        .addComponent(btAddI)))
                .addGap(18, 18, 18)
                .addGroup(imunViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBulanI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDeleteI)
                    .addComponent(btExportI)
                    .addComponent(lbBulanI, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imunView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imunView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbImunisasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbImunisasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbImunisasiActionPerformed

    private void btUpdateIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateIActionPerformed
        // TODO add your handling code here:
        if (tbImunisasi.getSelectedRowCount()==1){
        String upImunName=cbImunisasi.getSelectedItem().toString();
        String upDusunImun=tfNamaDusunI.getText();
        if (tfSasaranI.getText().isEmpty()) tfSasaranI.setText("0");
        if (tfPerolehanI.getText().isEmpty()) tfPerolehanI.setText("0");
        int upSasaranImun=Integer.parseInt(tfSasaranI.getText());
        int upPerolehanImun=Integer.parseInt(tfPerolehanI.getText());
        String upBulanImun=cbBulanI.getSelectedItem().toString();
        
        imunisasiList.get(row).imunName=upImunName;
        imunisasiList.get(row).dusunImun=upDusunImun;
        imunisasiList.get(row).sasaranImun=upSasaranImun;
        imunisasiList.get(row).perolehanImun=upPerolehanImun;
        imunisasiList.get(row).bulanImun=upBulanImun;
        imunisasiList.get(row).persentaseImun=(double)(upPerolehanImun*100.0/upSasaranImun);
        dtmi.setRowCount(0);
        for (int i=0; i<imunisasiList.size(); i++){
            Object[] objss={imunisasiList.get(i).imunName,imunisasiList.get(i).dusunImun,imunisasiList.get(i).sasaranImun,imunisasiList.get(i).perolehanImun,imunisasiList.get(i).bulanImun,imunisasiList.get(i).persentaseImun};
            dtmi.addRow(objss);
        }
        
        JOptionPane.showMessageDialog(rootPane, "Data berhasil diperbarui");
        
        }else{
            //kalau tabel kosong
            if(tbImunisasi.getRowCount()==0){
                JOptionPane.showMessageDialog(rootPane, "Maaf, tabel masih kosong");
            }else{
                JOptionPane.showMessageDialog(rootPane,"Mohon pilih salah satu tabel untuk diperbarui");
            }
        }
    }//GEN-LAST:event_btUpdateIActionPerformed

    private void btAddIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddIActionPerformed
        // TODO add your handling code here:
        try{
        String imunName=cbImunisasi.getSelectedItem().toString();
        String dusunImun=tfNamaDusunI.getText();
        int sasaranImun=Integer.parseInt(tfSasaranI.getText());
        int perolehanImun=Integer.parseInt(tfPerolehanI.getText());
        String bulanImun=cbBulanI.getSelectedItem().toString();
        double persentaseImun=(double)(perolehanImun*100.0/sasaranImun);
        imunisasiList.add(new Imunisasi(imunName,dusunImun,sasaranImun,perolehanImun,bulanImun,persentaseImun));
        dtmi.setRowCount(0);//reset
        for(int i=0;i<imunisasiList.size();i++){
            Object[] objss={imunisasiList.get(i).imunName,imunisasiList.get(i).dusunImun,imunisasiList.get(i).sasaranImun,imunisasiList.get(i).perolehanImun,imunisasiList.get(i).bulanImun,imunisasiList.get(i).persentaseImun};
            dtmi.addRow(objss);
        }
        
        //reset data
        clearFieldi();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Mohon isi semuanya sesuai ketentuan");
        }
    }//GEN-LAST:event_btAddIActionPerformed

    private void btDeleteIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteIActionPerformed
        // TODO add your handling code here:
        try{int dialogButton= JOptionPane.YES_NO_OPTION;
        int dialogResult= JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data ini", "Hapus", dialogButton);
        if(dialogResult==0){
        dtmi.removeRow(row);
        imunisasiList.remove(row);
        dtmi.setRowCount(0);
        for (int i=0; i<imunisasiList.size(); i++){
            Object[] objss={imunisasiList.get(i).imunName,imunisasiList.get(i).dusunImun,imunisasiList.get(i).sasaranImun,imunisasiList.get(i).perolehanImun,imunisasiList.get(i).bulanImun,imunisasiList.get(i).persentaseImun};
            dtmi.addRow(objss);
            
            }
            clearFieldi();
        }else{
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Maaf, data masih kosong");
        }
    }//GEN-LAST:event_btDeleteIActionPerformed

    private void tbImunisasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbImunisasiMouseClicked
        // TODO add your handling code here:
        row=tbImunisasi.getSelectedRow();
        col=tbImunisasi.getSelectedColumn();
        System.out.println(row+","+col);
        String imunisasiNama=dtmi.getValueAt(row, 0).toString();
        for(int i=0;i<(cbImunisasi.getItemCount());i++){
            if(cbImunisasi.getItemAt(i).equalsIgnoreCase(imunisasiNama)){
                cbImunisasi.setSelectedIndex(i);
            }
        }
        tfNamaDusunI.setText(dtmi.getValueAt(row,1).toString());
        tfSasaranI.setText(dtmi.getValueAt(row,2).toString());
        tfPerolehanI.setText(dtmi.getValueAt(row,3).toString());
        String bulanImunis=dtmi.getValueAt(row, 4).toString();
        for(int i=0;i<(cbBulanI.getItemCount());i++){
            if(cbBulanI.getItemAt(i).equalsIgnoreCase(bulanImunis)){
                cbBulanI.setSelectedIndex(i);
            }
        }
        dtmi.getValueAt(row, 5).toString();
    }//GEN-LAST:event_tbImunisasiMouseClicked
    private void openFile(String file){
        try{
            File path =new File(file);
            Desktop.getDesktop().open(path);
            
        }catch(IOException ioe){
            System.out.println(ioe);
        }
    }
    private void btExportIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExportIActionPerformed
        // TODO add your handling code here:
        try{
            JFileChooser jFile=new JFileChooser();
            jFile.showSaveDialog(this);
            File saveFile=jFile.getSelectedFile();
            if(saveFile!=null){
                saveFile=new File(saveFile.toString()+".xlsx");
                Workbook wbi=new XSSFWorkbook();
                Sheet sheet=wbi.createSheet("Rekap data Imunisasi");
                
                Row rowCol=sheet.createRow(0);
                for(int i=0;i<tbImunisasi.getColumnCount();i++){
                    Cell sel=rowCol.createCell(i);
                    sel.setCellValue(tbImunisasi.getColumnName(i));
                    
                }
                for(int j=0;j<tbImunisasi.getRowCount();j++){
                Row rowImun=sheet.createRow(j+1);
                for(int k=0;k<tbImunisasi.getColumnCount();k++){
                    Cell sel=rowImun.createCell(k);
                    if(tbImunisasi.getValueAt(j,k)!=null){
                        sel.setCellValue(tbImunisasi.getValueAt(j, k).toString());
                        }
                    }
                }
                FileOutputStream output=new FileOutputStream(new File(saveFile.toString()));
                wbi.write(output);
                wbi.close();
                output.close();
                openFile(saveFile.toString());
            }else{
                JOptionPane.showMessageDialog(null, "Terjadi Error saat proses arsip");
            }
        }catch(FileNotFoundException e){

              System.out.println(e);
        }catch (IOException io){
              System.out.println(io);
        }
        
    }//GEN-LAST:event_btExportIActionPerformed
    private void clearFieldi(){
        cbImunisasi.requestFocus();
        cbImunisasi.setSelectedIndex(0);
        tfNamaDusunI.setText("");
        tfSasaranI.setText("");
        tfPerolehanI.setText("");
        cbBulanI.setSelectedIndex(0);
        
        
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ImunisasiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ImunisasiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ImunisasiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ImunisasiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ImunisasiView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddI;
    private javax.swing.JButton btDeleteI;
    private javax.swing.JButton btExportI;
    private javax.swing.JButton btUpdateI;
    private javax.swing.JComboBox<String> cbBulanI;
    private javax.swing.JComboBox<String> cbImunisasi;
    private javax.swing.JPanel imunView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBulanI;
    private javax.swing.JLabel lbImunisasi;
    private javax.swing.JLabel lbNamaDusunI;
    private javax.swing.JLabel lbPerolehanI;
    private javax.swing.JLabel lbSasaranI;
    private javax.swing.JLabel lbTitleImunisasi;
    private javax.swing.JTable tbImunisasi;
    private javax.swing.JTextField tfNamaDusunI;
    private javax.swing.JTextField tfPerolehanI;
    private javax.swing.JTextField tfSasaranI;
    // End of variables declaration//GEN-END:variables
}
