/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package untan.ziman.rekapitulasikesehatanberingin;

import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author USER
 */
public class KeslingView extends javax.swing.JFrame {

    /**
     * Creates new form GiziView
     */
    ArrayList<Kesling> keslingList;
    String header[]=new String[]{"PWS Kesling","Nama Dusun","Sasaran","Perolehan","Bulan","Persentase"};
    DefaultTableModel dtms;
    int row,col;
    public KeslingView() {
        initComponents();
        keslingList=new ArrayList<>();
        dtms=new DefaultTableModel(header,0);
        tbKesling.setModel(dtms);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keslingView = new javax.swing.JPanel();
        lbTitleKesling = new javax.swing.JLabel();
        lbKesling = new javax.swing.JLabel();
        lbNamaDusunKes = new javax.swing.JLabel();
        lbSasaranKes = new javax.swing.JLabel();
        lbBulanKes = new javax.swing.JLabel();
        cbKesling = new javax.swing.JComboBox<>();
        cbBulanKes = new javax.swing.JComboBox<>();
        tfNmDusunKes = new javax.swing.JTextField();
        tfSasaranKes = new javax.swing.JTextField();
        lbPerolehanKes = new javax.swing.JLabel();
        tfPerolehanKes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKesling = new javax.swing.JTable();
        btAddKes = new javax.swing.JButton();
        btDeleteKes = new javax.swing.JButton();
        btUpdateKes = new javax.swing.JButton();
        btExportKes = new javax.swing.JButton();

        setTitle("Perhitungan Data Kesling");
        setResizable(false);

        keslingView.setBackground(new java.awt.Color(231, 76, 60));
        keslingView.setToolTipText("");
        keslingView.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        keslingView.setPreferredSize(new java.awt.Dimension(900, 700));

        lbTitleKesling.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        lbTitleKesling.setForeground(new java.awt.Color(0, 0, 0));
        lbTitleKesling.setText("Perhitungan PWS Kesehatan Lingkungan");

        lbKesling.setForeground(new java.awt.Color(0, 0, 0));
        lbKesling.setText("PWS Kesling : ");

        lbNamaDusunKes.setForeground(new java.awt.Color(0, 0, 0));
        lbNamaDusunKes.setText("Nama Dusun : ");

        lbSasaranKes.setForeground(new java.awt.Color(0, 0, 0));
        lbSasaranKes.setText("Sasaran : ");

        lbBulanKes.setForeground(new java.awt.Color(0, 0, 0));
        lbBulanKes.setText("Bulan : ");

        cbKesling.setBackground(new java.awt.Color(255, 255, 255));
        cbKesling.setForeground(new java.awt.Color(0, 0, 0));
        cbKesling.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cakupan Rumah Sehat", "Cakupan Air Bersih", "Cakupan Jamban Keluarga", "Cakupan SPAL", "Cakupan Angka Bebas Jentik" }));

        cbBulanKes.setBackground(new java.awt.Color(255, 255, 255));
        cbBulanKes.setForeground(new java.awt.Color(0, 0, 0));
        cbBulanKes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Januari", "2. Februari", "3. Maret", "4. April", "5. Mei", "6. Juni", "7. Juli", "8. Agustus", "9. September", "10. Oktober", "11. November", "12. Desember" }));
        cbBulanKes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBulanKesActionPerformed(evt);
            }
        });

        tfNmDusunKes.setBackground(new java.awt.Color(255, 255, 255));
        tfNmDusunKes.setForeground(new java.awt.Color(0, 0, 0));

        tfSasaranKes.setBackground(new java.awt.Color(255, 255, 255));
        tfSasaranKes.setForeground(new java.awt.Color(0, 0, 0));
        tfSasaranKes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSasaranKesActionPerformed(evt);
            }
        });

        lbPerolehanKes.setForeground(new java.awt.Color(0, 0, 0));
        lbPerolehanKes.setText("Perolehan : ");

        tfPerolehanKes.setBackground(new java.awt.Color(255, 255, 255));
        tfPerolehanKes.setForeground(new java.awt.Color(0, 0, 0));

        tbKesling.setBackground(new java.awt.Color(255, 255, 255));
        tbKesling.setForeground(new java.awt.Color(0, 0, 0));
        tbKesling.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PWS Kesling", "Nama Dusun", "Sasaran", "Perolehan", "Bulan", "Persentase"
            }
        ));
        tbKesling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKeslingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKesling);

        btAddKes.setForeground(new java.awt.Color(0, 0, 0));
        btAddKes.setText("Add");
        btAddKes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddKesActionPerformed(evt);
            }
        });

        btDeleteKes.setForeground(new java.awt.Color(0, 0, 0));
        btDeleteKes.setText("Delete");
        btDeleteKes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteKesActionPerformed(evt);
            }
        });

        btUpdateKes.setForeground(new java.awt.Color(0, 0, 0));
        btUpdateKes.setText("Update");
        btUpdateKes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateKesActionPerformed(evt);
            }
        });

        btExportKes.setForeground(new java.awt.Color(0, 0, 0));
        btExportKes.setText("Export to .xlsx");
        btExportKes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExportKesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout keslingViewLayout = new javax.swing.GroupLayout(keslingView);
        keslingView.setLayout(keslingViewLayout);
        keslingViewLayout.setHorizontalGroup(
            keslingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keslingViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(keslingViewLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(keslingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTitleKesling)
                    .addGroup(keslingViewLayout.createSequentialGroup()
                        .addGroup(keslingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbNamaDusunKes)
                            .addComponent(lbKesling)
                            .addComponent(lbSasaranKes)
                            .addComponent(lbPerolehanKes)
                            .addComponent(lbBulanKes))
                        .addGap(31, 31, 31)
                        .addGroup(keslingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbBulanKes, 0, 251, Short.MAX_VALUE)
                            .addComponent(cbKesling, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSasaranKes)
                            .addComponent(tfNmDusunKes)
                            .addComponent(tfPerolehanKes))
                        .addGap(90, 90, 90)
                        .addGroup(keslingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btDeleteKes, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(btAddKes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(keslingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(keslingViewLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btUpdateKes, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(keslingViewLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btExportKes)))
                .addGap(127, 139, Short.MAX_VALUE))
        );
        keslingViewLayout.setVerticalGroup(
            keslingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keslingViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitleKesling)
                .addGap(45, 45, 45)
                .addGroup(keslingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbKesling)
                    .addComponent(cbKesling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(keslingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNamaDusunKes)
                    .addComponent(tfNmDusunKes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(keslingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSasaranKes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSasaranKes))
                .addGap(18, 18, 18)
                .addGroup(keslingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPerolehanKes)
                    .addComponent(tfPerolehanKes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddKes)
                    .addComponent(btUpdateKes))
                .addGap(18, 18, 18)
                .addGroup(keslingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBulanKes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBulanKes)
                    .addComponent(btDeleteKes)
                    .addComponent(btExportKes))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(keslingView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(keslingView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfSasaranKesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSasaranKesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSasaranKesActionPerformed

    private void cbBulanKesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBulanKesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBulanKesActionPerformed

    private void btDeleteKesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteKesActionPerformed
        // TODO add your handling code here:
        try{
        int dialogButton= JOptionPane.YES_NO_OPTION;
        int dialogResult= JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data ini", "Hapus", dialogButton);
        if(dialogResult==0){
        dtms.removeRow(row);
        keslingList.remove(row);
        dtms.setRowCount(0);
        for (int i=0; i<keslingList.size(); i++){
            Object[] objst={keslingList.get(i).keslingName,keslingList.get(i).dusunKesling,keslingList.get(i).sasaranKesling,keslingList.get(i).perolehanKesling,keslingList.get(i).bulanKesling,keslingList.get(i).persentaseKesling};
            dtms.addRow(objst);
            
            }
            clearFields();
        }else{
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Maaf, data masih kosong");
        }
    }//GEN-LAST:event_btDeleteKesActionPerformed
    private void openFile(String file){
        try{
            File path =new File(file);
            Desktop.getDesktop().open(path);
            
        }catch(IOException ioe){
            System.out.println(ioe);
        }
    }
    private void btExportKesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExportKesActionPerformed
        // TODO add your handling code here:
        try{
            JFileChooser jFile=new JFileChooser();
            jFile.showSaveDialog(this);
            File saveFile=jFile.getSelectedFile();
            if(saveFile!=null){
                saveFile=new File(saveFile.toString()+".xlsx");
                Workbook wbk=new XSSFWorkbook();
                Sheet sheet=wbk.createSheet("Rekap data Kesling");
                
                Row rowCol=sheet.createRow(0);
                for(int i=0;i<tbKesling.getColumnCount();i++){
                    Cell sel=rowCol.createCell(i);
                    sel.setCellValue(tbKesling.getColumnName(i));
                    
                }
                for(int j=0;j<tbKesling.getRowCount();j++){
                Row rowk=sheet.createRow(j+1);
                for(int k=0;k<tbKesling.getColumnCount();k++){
                    Cell sel=rowk.createCell(k);
                    if(tbKesling.getValueAt(j,k)!=null){
                        sel.setCellValue(tbKesling.getValueAt(j, k).toString());
                        }
                    }
                }
                FileOutputStream output=new FileOutputStream(new File(saveFile.toString()));
                wbk.write(output);
                wbk.close();
                output.close();
                openFile(saveFile.toString());
            }else{
                JOptionPane.showMessageDialog(null, "Terjadi Error saat proses arsip");
            }
        }catch(FileNotFoundException e){
              System.out.println(e);
        }catch (IOException io){
              System.out.println(io);
        }
    }//GEN-LAST:event_btExportKesActionPerformed

    private void btAddKesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddKesActionPerformed
        // TODO add your handling code here:
        try{
        String keslingName=cbKesling.getSelectedItem().toString();
        String dusunKesling=tfNmDusunKes.getText();
        int sasaranKesling=Integer.parseInt(tfSasaranKes.getText());
        int perolehanKesling=Integer.parseInt(tfPerolehanKes.getText());
        String bulanKesling=cbBulanKes.getSelectedItem().toString();
        double persentaseKesling=(double)(perolehanKesling*100.0/sasaranKesling);
        keslingList.add(new Kesling(keslingName,dusunKesling,sasaranKesling,perolehanKesling,bulanKesling,persentaseKesling));
        dtms.setRowCount(0);//reset
        for(int i=0;i<keslingList.size();i++){
            Object[] objst={keslingList.get(i).keslingName,keslingList.get(i).dusunKesling,keslingList.get(i).sasaranKesling,keslingList.get(i).perolehanKesling,keslingList.get(i).bulanKesling,keslingList.get(i).persentaseKesling};
            dtms.addRow(objst);
        }
        
        //reset data
        clearFields();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Mohon isi semuanya sesuai ketentuan");
        }
    }//GEN-LAST:event_btAddKesActionPerformed

    private void btUpdateKesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateKesActionPerformed
        // TODO add your handling code here:
        if (tbKesling.getSelectedRowCount()==1){
        String upKeslingName=cbKesling.getSelectedItem().toString();
        String upDusunKesling=tfNmDusunKes.getText();
        if (tfSasaranKes.getText().isEmpty()) tfSasaranKes.setText("0");
        if (tfPerolehanKes.getText().isEmpty()) tfPerolehanKes.setText("0");
        int upSasaranKes=Integer.parseInt(tfSasaranKes.getText());
        int upPerolehanKes=Integer.parseInt(tfPerolehanKes.getText());
        String upBulanKes=cbBulanKes.getSelectedItem().toString();
        
        keslingList.get(row).keslingName=upKeslingName;
        keslingList.get(row).dusunKesling=upDusunKesling;
        keslingList.get(row).sasaranKesling=upSasaranKes;
        keslingList.get(row).perolehanKesling=upPerolehanKes;
        keslingList.get(row).bulanKesling=upBulanKes;
        keslingList.get(row).persentaseKesling=(double)(upPerolehanKes*100.0/upSasaranKes);
        dtms.setRowCount(0);
        for (int i=0; i<keslingList.size(); i++){
            Object[] objst={keslingList.get(i).keslingName,keslingList.get(i).dusunKesling,keslingList.get(i).sasaranKesling,keslingList.get(i).perolehanKesling,keslingList.get(i).bulanKesling,keslingList.get(i).persentaseKesling};
            dtms.addRow(objst);
        }
        
        JOptionPane.showMessageDialog(rootPane, "Data berhasil diperbarui");
        
        }else{
            //kalau tabel kosong
            if(tbKesling.getRowCount()==0){
                JOptionPane.showMessageDialog(rootPane, "Maaf, tabel masih kosong");
            }else{
                JOptionPane.showMessageDialog(rootPane,"Mohon pilih salah satu tabel untuk diperbarui");
            }
        }
    }//GEN-LAST:event_btUpdateKesActionPerformed

    private void tbKeslingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKeslingMouseClicked
        // TODO add your handling code here:
        row=tbKesling.getSelectedRow();
        col=tbKesling.getSelectedColumn();
        System.out.println(row+","+col);
        String keslingNama=dtms.getValueAt(row, 0).toString();
        for(int i=0;i<(cbKesling.getItemCount());i++){
            if(cbKesling.getItemAt(i).equalsIgnoreCase(keslingNama)){
                cbKesling.setSelectedIndex(i);
            }
        }
        tfNmDusunKes.setText(dtms.getValueAt(row,1).toString());
        tfSasaranKes.setText(dtms.getValueAt(row,2).toString());
        tfPerolehanKes.setText(dtms.getValueAt(row,3).toString());
        String bulanKess=dtms.getValueAt(row, 4).toString();
        for(int i=0;i<(cbBulanKes.getItemCount());i++){
            if(cbBulanKes.getItemAt(i).equalsIgnoreCase(bulanKess)){
                cbBulanKes.setSelectedIndex(i);
            }
        }
        dtms.getValueAt(row, 5).toString();
    }//GEN-LAST:event_tbKeslingMouseClicked
    private void clearFields(){
        cbKesling.requestFocus();
        cbKesling.setSelectedIndex(0);
        tfNmDusunKes.setText("");
        tfSasaranKes.setText("");
        tfPerolehanKes.setText("");
        cbBulanKes.setSelectedIndex(0);
        
        
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KeslingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KeslingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KeslingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KeslingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new KeslingView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddKes;
    private javax.swing.JButton btDeleteKes;
    private javax.swing.JButton btExportKes;
    private javax.swing.JButton btUpdateKes;
    private javax.swing.JComboBox<String> cbBulanKes;
    private javax.swing.JComboBox<String> cbKesling;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel keslingView;
    private javax.swing.JLabel lbBulanKes;
    private javax.swing.JLabel lbKesling;
    private javax.swing.JLabel lbNamaDusunKes;
    private javax.swing.JLabel lbPerolehanKes;
    private javax.swing.JLabel lbSasaranKes;
    private javax.swing.JLabel lbTitleKesling;
    private javax.swing.JTable tbKesling;
    private javax.swing.JTextField tfNmDusunKes;
    private javax.swing.JTextField tfPerolehanKes;
    private javax.swing.JTextField tfSasaranKes;
    // End of variables declaration//GEN-END:variables
}
