/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package untan.ziman.rekapitulasikesehatanberingin;


import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author USER
 */
public class KiaView extends javax.swing.JFrame {

    /**
     * Creates new form KiaView
     */
    ArrayList<KIA> kiaList;
    String header[]=new String[]{"PWS KIA","Nama Dusun","Sasaran","Perolehan","Bulan","Persentase"};
    DefaultTableModel dtm;
    int row,col;
    public KiaView() {
        initComponents();
        kiaList=new ArrayList<>();
        dtm=new DefaultTableModel(header,0);
        tbKia.setModel(dtm);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kiaView = new javax.swing.JPanel();
        lbKia = new javax.swing.JLabel();
        lbNamaDusunK = new javax.swing.JLabel();
        lbsasaranK = new javax.swing.JLabel();
        lbBulanK = new javax.swing.JLabel();
        cbPwsK = new javax.swing.JComboBox<>();
        tfNamaDusun = new javax.swing.JTextField();
        lbTitleKia = new javax.swing.JLabel();
        cbBulan = new javax.swing.JComboBox<>();
        tfSasaranK = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKia = new javax.swing.JTable();
        lbPerolehanK = new javax.swing.JLabel();
        tfPerolehanK = new javax.swing.JTextField();
        btAddK = new javax.swing.JButton();
        btDeleteK = new javax.swing.JButton();
        btUpdateK = new javax.swing.JButton();
        btExportK = new javax.swing.JButton();

        setTitle("Perhitungan Data KIA");
        setResizable(false);

        kiaView.setBackground(new java.awt.Color(26, 188, 156));
        kiaView.setName("Perhitungan KIA"); // NOI18N
        kiaView.setPreferredSize(new java.awt.Dimension(700, 468));

        lbKia.setForeground(new java.awt.Color(0, 0, 0));
        lbKia.setText("PWS KIA : ");

        lbNamaDusunK.setForeground(new java.awt.Color(0, 0, 0));
        lbNamaDusunK.setText("Nama Dusun : ");

        lbsasaranK.setForeground(new java.awt.Color(0, 0, 0));
        lbsasaranK.setText("Sasaran :");

        lbBulanK.setForeground(new java.awt.Color(0, 0, 0));
        lbBulanK.setText("Bulan : ");

        cbPwsK.setBackground(new java.awt.Color(255, 255, 255));
        cbPwsK.setForeground(new java.awt.Color(0, 0, 0));
        cbPwsK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cakupan pelayanan antenatal (cakupan K1)", "Cakupan pelayanan ibu hamil (cakupan K4)", "Cakupan persalinan oleh tenaga kesehatan (Pn)", "Cakupan pelayanan nifas oleh tenaga kesehatan (KF3)", "Cakupan pelananan neonatus pertama (KN1)", "Cakupan pelayanan kesehatan neonatus 0-28 hari (KNL Lengkap)", "Deteksi Faktor risiko dan komlpikasi oleh Masyarakat", "Cakupan Penanganan komplikasi Obstetri (PK)", "Cakupan penanganan komplikasi neonatus ", "Cakupan pelayanan kesehatan bayi 29 hari - 12 bulan (Kunjungan Bayi)", "Cakupan Pelayanan anak balita (12 - 59 bulan)", "Cakupan Pelayanan kesehatan anak balita sakit yang dilayani dengan MTBS", "Cakupan peserta KB Aktif (Contraceptive Prevalence Rate)" }));
        cbPwsK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPwsKActionPerformed(evt);
            }
        });

        tfNamaDusun.setBackground(new java.awt.Color(255, 255, 255));
        tfNamaDusun.setForeground(new java.awt.Color(0, 0, 0));

        lbTitleKia.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        lbTitleKia.setForeground(new java.awt.Color(0, 0, 0));
        lbTitleKia.setText("Perhitungan PWS KIA");

        cbBulan.setBackground(new java.awt.Color(255, 255, 255));
        cbBulan.setForeground(new java.awt.Color(0, 0, 0));
        cbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Januari", "2. Februari", "3. Maret", "4. April", "5. Mei", "6. Juni", "7. Juli", "8. Agustus", "9. September", "10. Oktober", "11. November", "12. Desember" }));
        cbBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBulanActionPerformed(evt);
            }
        });

        tfSasaranK.setBackground(new java.awt.Color(255, 255, 255));
        tfSasaranK.setForeground(new java.awt.Color(0, 0, 0));
        tfSasaranK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSasaranKActionPerformed(evt);
            }
        });

        tbKia.setBackground(new java.awt.Color(255, 255, 255));
        tbKia.setForeground(new java.awt.Color(0, 0, 0));
        tbKia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PWS KIA", "Nama Dusun", "Sasaran", "Perolehan", "Bulan", "Persentase"
            }
        ));
        tbKia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbKia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKia);

        lbPerolehanK.setForeground(new java.awt.Color(0, 0, 0));
        lbPerolehanK.setText("Perolehan : ");

        tfPerolehanK.setBackground(new java.awt.Color(255, 255, 255));
        tfPerolehanK.setForeground(new java.awt.Color(0, 0, 0));

        btAddK.setForeground(new java.awt.Color(0, 0, 0));
        btAddK.setText("Add");
        btAddK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddKActionPerformed(evt);
            }
        });

        btDeleteK.setForeground(new java.awt.Color(0, 0, 0));
        btDeleteK.setText("Delete");
        btDeleteK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteKActionPerformed(evt);
            }
        });

        btUpdateK.setForeground(new java.awt.Color(0, 0, 0));
        btUpdateK.setText("Update");
        btUpdateK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateKActionPerformed(evt);
            }
        });

        btExportK.setForeground(new java.awt.Color(0, 0, 0));
        btExportK.setText("Export to .xlsx");
        btExportK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExportKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kiaViewLayout = new javax.swing.GroupLayout(kiaView);
        kiaView.setLayout(kiaViewLayout);
        kiaViewLayout.setHorizontalGroup(
            kiaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kiaViewLayout.createSequentialGroup()
                .addGroup(kiaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kiaViewLayout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(lbTitleKia))
                    .addGroup(kiaViewLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kiaViewLayout.createSequentialGroup()
                        .addGroup(kiaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kiaViewLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(kiaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(kiaViewLayout.createSequentialGroup()
                                        .addComponent(lbBulanK)
                                        .addGap(62, 62, 62))
                                    .addGroup(kiaViewLayout.createSequentialGroup()
                                        .addComponent(lbKia)
                                        .addGap(57, 57, 57))))
                            .addGroup(kiaViewLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(kiaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbNamaDusunK)
                                    .addComponent(lbsasaranK, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPerolehanK, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)))
                        .addGroup(kiaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSasaranK, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kiaViewLayout.createSequentialGroup()
                                .addGroup(kiaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kiaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfPerolehanK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbBulan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfNamaDusun, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(98, 98, 98)
                                .addGroup(kiaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btAddK, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(btDeleteK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(kiaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btExportK)
                                    .addComponent(btUpdateK, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cbPwsK, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        kiaViewLayout.setVerticalGroup(
            kiaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kiaViewLayout.createSequentialGroup()
                .addGroup(kiaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kiaViewLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTitleKia))
                    .addGroup(kiaViewLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(kiaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbKia)
                            .addComponent(cbPwsK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(kiaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNamaDusunK)
                    .addComponent(tfNamaDusun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kiaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbsasaranK)
                    .addComponent(tfSasaranK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kiaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPerolehanK)
                    .addComponent(tfPerolehanK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddK)
                    .addComponent(btUpdateK))
                .addGap(18, 18, 18)
                .addGroup(kiaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBulanK)
                    .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDeleteK)
                    .addComponent(btExportK))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kiaView, javax.swing.GroupLayout.DEFAULT_SIZE, 900, 900)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kiaView, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfSasaranKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSasaranKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSasaranKActionPerformed

    private void cbBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBulanActionPerformed

    private void cbPwsKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPwsKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPwsKActionPerformed

    private void btAddKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddKActionPerformed
        // TODO add your handling code here:
        try{
        String KiaName=cbPwsK.getSelectedItem().toString();
        String dusunKia=tfNamaDusun.getText();
        int sasaranKia=Integer.parseInt(tfSasaranK.getText());
        int perolehanKia=Integer.parseInt(tfPerolehanK.getText());
        String bulanKia=cbBulan.getSelectedItem().toString();
        double persentaseKia=(double)(perolehanKia*100.0/sasaranKia);
        kiaList.add(new KIA(KiaName,dusunKia,sasaranKia,perolehanKia,bulanKia,persentaseKia));
        dtm.setRowCount(0);//menentukan ulang jumlah baris di tabel model
        //looping for supaya bisa ditambahkan data terus-menerus
        for(int i=0;i<kiaList.size();i++){
            Object[] objs={kiaList.get(i).KiaName,kiaList.get(i).dusunKia,kiaList.get(i).sasaranKia,kiaList.get(i).perolehanKia,kiaList.get(i).bulanKia,kiaList.get(i).persentaseKia};
            dtm.addRow(objs);
        }
        
        //reset data di combo box dan textfield setelah data ditambahkan
        clearField();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Mohon isi semuanya sesuai ketentuan");
        }  
        
    }//GEN-LAST:event_btAddKActionPerformed
    private void clearField(){
        cbPwsK.requestFocus();
        cbPwsK.setSelectedIndex(0);
        tfNamaDusun.setText("");
        tfSasaranK.setText("");
        tfPerolehanK.setText("");
        cbBulan.setSelectedIndex(0);
    }
    
    private void btDeleteKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteKActionPerformed
        // TODO add your handling code here:
        try{
        int dialogButton= JOptionPane.YES_NO_OPTION;
        int dialogResult= JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data ini", "Hapus", dialogButton);
        if(dialogResult==0){
        dtm.removeRow(row);
        kiaList.remove(row);
        dtm.setRowCount(0);
        for (int i=0; i<kiaList.size(); i++){
            Object[] objs={kiaList.get(i).KiaName,kiaList.get(i).dusunKia,kiaList.get(i).sasaranKia,kiaList.get(i).perolehanKia,kiaList.get(i).bulanKia,kiaList.get(i).persentaseKia};
            dtm.addRow(objs);
            
            }
            clearField();
        }else{
            
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Maaf, data masih kosong");
        }
    }//GEN-LAST:event_btDeleteKActionPerformed

    private void btUpdateKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateKActionPerformed
        // TODO add your handling code here:
        //try{
        if (tbKia.getSelectedRowCount()==1){
        String upKiaName=cbPwsK.getSelectedItem().toString();
        String upDusunKia=tfNamaDusun.getText();
        if (tfSasaranK.getText().isEmpty()) tfSasaranK.setText("0");
        if (tfPerolehanK.getText().isEmpty()) tfPerolehanK.setText("0");
        int upSasaranKia=Integer.parseInt(tfSasaranK.getText());
        int upPerolehanKia=Integer.parseInt(tfPerolehanK.getText());
        String upBulanKia=cbBulan.getSelectedItem().toString();
        
        kiaList.get(row).KiaName=upKiaName;
        kiaList.get(row).dusunKia=upDusunKia;
        kiaList.get(row).sasaranKia=upSasaranKia;
        kiaList.get(row).perolehanKia=upPerolehanKia;
        kiaList.get(row).bulanKia=upBulanKia;
        kiaList.get(row).persentaseKia=(double)(upPerolehanKia*100.0/upSasaranKia);
        dtm.setRowCount(0);//menentukan ulang jumlah baris
        for (int i=0; i<kiaList.size(); i++){
            Object[] objs={kiaList.get(i).KiaName,kiaList.get(i).dusunKia,kiaList.get(i).sasaranKia,kiaList.get(i).perolehanKia,kiaList.get(i).bulanKia,kiaList.get(i).persentaseKia};
            dtm.addRow(objs);
        }
        JOptionPane.showMessageDialog(rootPane, "Data berhasil diperbarui");
        
        }else{
            //kalau tabel kosong
            if(tbKia.getRowCount()==0){
                JOptionPane.showMessageDialog(rootPane,"Maaf, tabel masih kosong");
            }else{
                JOptionPane.showMessageDialog(rootPane,"Mohon pilih salah satu tabel untuk diperbarui");
            }
        }
        
    }//GEN-LAST:event_btUpdateKActionPerformed
    private void openFile(String file){
        try{
            File path =new File(file);
            Desktop.getDesktop().open(path);
            
        }catch(IOException ioe){
            System.out.println(ioe);
        }
    }
    private void btExportKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExportKActionPerformed
        // TODO add your handling code here:
        try{
            JFileChooser jFile=new JFileChooser();
            jFile.showSaveDialog(this);
            File saveFile=jFile.getSelectedFile();
            if(saveFile!=null){
                saveFile=new File(saveFile.toString()+".xlsx");//memberi format .xlsx
                Workbook wb=new XSSFWorkbook();
                Sheet sheet=wb.createSheet("Rekap data KIA");
                
                Row rowCol=sheet.createRow(0);  //dibuat di baris pertama atau index 0
                for(int i=0;i<tbKia.getColumnCount();i++){  //untuk penamaan header kolom
                    Cell sel=rowCol.createCell(i);
                    sel.setCellValue(tbKia.getColumnName(i));
                    
                }
                for(int j=0;j<tbKia.getRowCount();j++){
                Row rowKia=sheet.createRow(j+1);
                for(int k=0;k<tbKia.getColumnCount();k++){
                    Cell sel=rowKia.createCell(k);
                    if(tbKia.getValueAt(j,k)!=null){
                        sel.setCellValue(tbKia.getValueAt(j, k).toString());
                        }
                    }
                }
                FileOutputStream output=new FileOutputStream(new File(saveFile.toString()));
                wb.write(output);//menulis nama file
                wb.close();//menutup akses/proses pada workbook
                output.close();//menutup akses file
                openFile(saveFile.toString());//auto open file setelah export
            }else{
                JOptionPane.showMessageDialog(null, "Terjadi Error saat proses arsip");
            }
        }catch(FileNotFoundException e){
              System.out.println(e);
        }catch (IOException io){
              System.out.println(io);
        }
    }//GEN-LAST:event_btExportKActionPerformed

    private void tbKiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKiaMouseClicked
        // TODO add your handling code here:
        row=tbKia.getSelectedRow();
        col=tbKia.getSelectedColumn();
        System.out.println(row+","+col); //untuk melihat indeks pada terminal
        String pwsKias=dtm.getValueAt(row, 0).toString();//pada tabel
        for(int i=0;i<(cbPwsK.getItemCount());i++){
            if(cbPwsK.getItemAt(i).equalsIgnoreCase(pwsKias)){
                cbPwsK.setSelectedIndex(i);
            }
        }
        tfNamaDusun.setText(dtm.getValueAt(row,1).toString());
        tfSasaranK.setText(dtm.getValueAt(row,2).toString());
        tfPerolehanK.setText(dtm.getValueAt(row,3).toString());
        String bulanKias=dtm.getValueAt(row, 4).toString();
        for(int i=0;i<(cbBulan.getItemCount());i++){
            if(cbBulan.getItemAt(i).equalsIgnoreCase(bulanKias)){
                cbBulan.setSelectedIndex(i);
            }
        }
        dtm.getValueAt(row, 5).toString();
    }//GEN-LAST:event_tbKiaMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new KiaView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddK;
    private javax.swing.JButton btDeleteK;
    private javax.swing.JButton btExportK;
    private javax.swing.JButton btUpdateK;
    private javax.swing.JComboBox<String> cbBulan;
    private javax.swing.JComboBox<String> cbPwsK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel kiaView;
    private javax.swing.JLabel lbBulanK;
    private javax.swing.JLabel lbKia;
    private javax.swing.JLabel lbNamaDusunK;
    private javax.swing.JLabel lbPerolehanK;
    private javax.swing.JLabel lbTitleKia;
    private javax.swing.JLabel lbsasaranK;
    private javax.swing.JTable tbKia;
    private javax.swing.JTextField tfNamaDusun;
    private javax.swing.JTextField tfPerolehanK;
    private javax.swing.JTextField tfSasaranK;
    // End of variables declaration//GEN-END:variables
}
