/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package untan.ziman.rekapitulasikesehatanberingin;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backView = new javax.swing.JPanel();
        logoBakti = new javax.swing.JLabel();
        btKia = new javax.swing.JButton();
        btImunisasi = new javax.swing.JButton();
        btKesling = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        titleMenu = new javax.swing.JPanel();
        labTitle = new javax.swing.JLabel();
        labTitle2 = new javax.swing.JLabel();
        labTitle3 = new javax.swing.JLabel();
        logoPuskesmas = new javax.swing.JLabel();
        btAbout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Rekapitulasi Kesehatan");
        setPreferredSize(new java.awt.Dimension(900, 700));
        setResizable(false);

        backView.setBackground(new java.awt.Color(52, 152, 219));
        backView.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backView.setName("Menu"); // NOI18N
        backView.setPreferredSize(new java.awt.Dimension(900, 700));

        logoBakti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/untan/ziman/rekapitulasikesehatanberingin/Logo Bakti Husada, Lambang Kesehatan untuk Upaya Kesehatan2.png"))); // NOI18N

        btKia.setBackground(new java.awt.Color(0, 148, 50));
        btKia.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btKia.setForeground(new java.awt.Color(255, 255, 255));
        btKia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/untan/ziman/rekapitulasikesehatanberingin/icons8-working-mom-50.png"))); // NOI18N
        btKia.setText("KIA");
        btKia.setAlignmentX(0.5F);
        btKia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btKia.setIconTextGap(10);
        btKia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKiaActionPerformed(evt);
            }
        });

        btImunisasi.setBackground(new java.awt.Color(111, 30, 81));
        btImunisasi.setFont(new java.awt.Font("Roboto Slab Medium", 0, 12)); // NOI18N
        btImunisasi.setForeground(new java.awt.Color(255, 255, 255));
        btImunisasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/untan/ziman/rekapitulasikesehatanberingin/icons8-insulin-pen-64.png"))); // NOI18N
        btImunisasi.setText("Imunisasi");
        btImunisasi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btImunisasi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btImunisasi.setIconTextGap(10);
        btImunisasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImunisasiActionPerformed(evt);
            }
        });

        btKesling.setBackground(new java.awt.Color(192, 57, 43));
        btKesling.setFont(new java.awt.Font("Roboto Slab Medium", 0, 12)); // NOI18N
        btKesling.setForeground(new java.awt.Color(255, 255, 255));
        btKesling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/untan/ziman/rekapitulasikesehatanberingin/icons8-forest-23.png"))); // NOI18N
        btKesling.setText("Kesling");
        btKesling.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btKesling.setIconTextGap(10);
        btKesling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeslingActionPerformed(evt);
            }
        });

        btExit.setBackground(new java.awt.Color(59, 59, 152));
        btExit.setFont(new java.awt.Font("Roboto Slab Medium", 0, 12)); // NOI18N
        btExit.setForeground(new java.awt.Color(255, 255, 255));
        btExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/untan/ziman/rekapitulasikesehatanberingin/logout (1).png"))); // NOI18N
        btExit.setText("Exit");
        btExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btExit.setIconTextGap(10);
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        titleMenu.setBackground(new java.awt.Color(231, 76, 60));
        titleMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        labTitle.setFont(new java.awt.Font("Cormorant Infant Medium", 1, 16)); // NOI18N
        labTitle.setForeground(new java.awt.Color(255, 255, 255));
        labTitle.setText("Selamat Datang Di Aplikasi Rekapitulasi Data");

        labTitle2.setFont(new java.awt.Font("Cormorant Infant Medium", 1, 16)); // NOI18N
        labTitle2.setForeground(new java.awt.Color(255, 255, 255));
        labTitle2.setText("Pemantauan Wilayah Setempat(PWS)");

        labTitle3.setFont(new java.awt.Font("Cormorant Infant Medium", 1, 16)); // NOI18N
        labTitle3.setForeground(new java.awt.Color(255, 255, 255));
        labTitle3.setText("Di Desa Beringin");

        javax.swing.GroupLayout titleMenuLayout = new javax.swing.GroupLayout(titleMenu);
        titleMenu.setLayout(titleMenuLayout);
        titleMenuLayout.setHorizontalGroup(
            titleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleMenuLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(titleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleMenuLayout.createSequentialGroup()
                        .addGroup(titleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleMenuLayout.createSequentialGroup()
                        .addComponent(labTitle3)
                        .addGap(157, 157, 157))))
        );
        titleMenuLayout.setVerticalGroup(
            titleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleMenuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labTitle3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logoPuskesmas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/untan/ziman/rekapitulasikesehatanberingin/kisspng-puskesmas-regency-bengkulu-health-logo-tulisan-5b124943b4b423.5236810415279250597402.png"))); // NOI18N

        btAbout.setBackground(new java.awt.Color(0, 153, 153));
        btAbout.setFont(new java.awt.Font("Roboto Slab Medium", 0, 12)); // NOI18N
        btAbout.setForeground(new java.awt.Color(255, 255, 255));
        btAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/untan/ziman/rekapitulasikesehatanberingin/icons8-about-64.png"))); // NOI18N
        btAbout.setText("About");
        btAbout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btAbout.setIconTextGap(10);
        btAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backViewLayout = new javax.swing.GroupLayout(backView);
        backView.setLayout(backViewLayout);
        backViewLayout.setHorizontalGroup(
            backViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backViewLayout.createSequentialGroup()
                .addGroup(backViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backViewLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addGroup(backViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btKia, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btImunisasi, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btKesling, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backViewLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(logoBakti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoPuskesmas, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        backViewLayout.setVerticalGroup(
            backViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backViewLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(backViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoBakti)
                    .addComponent(titleMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoPuskesmas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addComponent(btKia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btImunisasi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btKesling, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backView, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        backView.getAccessibleContext().setAccessibleDescription("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btImunisasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImunisasiActionPerformed
        // TODO add your handling code here:
        ImunisasiView imun =new ImunisasiView();
        imun.setVisible(true);
    }//GEN-LAST:event_btImunisasiActionPerformed

    private void btKeslingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeslingActionPerformed
        // TODO add your handling code here:
        KeslingView gizi=new KeslingView();
        gizi.setVisible(true);
    }//GEN-LAST:event_btKeslingActionPerformed

    private void btAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAboutActionPerformed
        // TODO add your handling code here:
        AboutView about= new AboutView();
        about.setVisible(true);
    }//GEN-LAST:event_btAboutActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:
        int dialogBtn= JOptionPane.YES_NO_OPTION;
        int dialogResult= JOptionPane.showConfirmDialog(this, "Anda yakin ingin keluar", "PERINGATAN", dialogBtn);
        
        if(dialogResult==0){
        System.exit(0);
        }else{
            
        }
    }//GEN-LAST:event_btExitActionPerformed

    private void btKiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKiaActionPerformed
        // TODO add your handling code here:
        KiaView kia=new KiaView();
        kia.setVisible(true);
    }//GEN-LAST:event_btKiaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backView;
    private javax.swing.JButton btAbout;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btImunisasi;
    private javax.swing.JButton btKesling;
    private javax.swing.JButton btKia;
    private javax.swing.JLabel labTitle;
    private javax.swing.JLabel labTitle2;
    private javax.swing.JLabel labTitle3;
    private javax.swing.JLabel logoBakti;
    private javax.swing.JLabel logoPuskesmas;
    private javax.swing.JPanel titleMenu;
    // End of variables declaration//GEN-END:variables
}
